#!/usr/bin/perl -w
#

use strict;


my $test
    = {
       command_definitions => [
			       {
				arguments => [
					     ],
				command => 'bin/genesis-g3',
				command_tests => [
						  {
						   description => "Is startup successful ?",
						   read => "GENESIS 3 shell",
						   timeout => 5,
						  },
						  {
						   description => "Can we find information about the different verbosity levels ?",
						   read => "verbosity levels:
  debug:
    description: used for software development and maintenance
  errors:
    description: display only error state information (an error state makes it impossible for an application to complete)
  information:
    description: 'display information, warning and error messages (lists messages about important events generated by an application)'
  warnings:
    comment: this is the default
    description: display warning and error state information (a warning state allows an application to continue but you should thoroughly check any output)
",
						   timeout => 5,
						   write => 'list verbose',
						  },
						  {
						   description => "Does the verbose_level variable have a legal value ?",
						   read => "
verbose_level: warnings
",
						   write => "show_verbose",
						  },
						  {
						   description => "Can we set the verbose_level variable to a different legal value ?",
						   write => "set_verbose debug",
						  },
						  {
						   description => "Does the verbose_level variable have this new legal value ?",
						   read => "
verbose_level: debug
",
						   write => "show_verbose",
						  },
						  {
						   description => "Can we set the verbose_level variable to an illegal value ?",
						   read => "*** Error: verbosity texan_deadbeaf does not exist in the current environment",
						   write => "set_verbose texan_deadbeaf",
						  },
						  {
						   description => "Does the verbose_level variable have this illegal value (should not) ?",
						   read => "
verbose_level: debug
",
						   write => "show_verbose",
						  },
						 ],
				description => "verbose variable",
			       },
			      ],
       description => "variables",
       name => 'variables.t',
      };


return $test;


