#!/usr/bin/perl -w
#!/usr/bin/perl -d:ptkdb
#!


use strict;


BEGIN
{
    #! make check

    push @INC, '../perl';

    #! make distcheck

    push @INC, '../../perl';

    #! normal run

    push @INC, './perl';

    #! after install

    push @INC, '/usr/local/glue/swig/perl';
}


BEGIN
{
    $ENV{NEUROSPACES_NMC_MODELS} = '/usr/local/neurospaces/models/library';
}


$SIG{__DIE__}
    = sub {
	use Carp;

	confess @_;
    };


package GENESIS3::Commands;


sub new_command
{
    my $argument = shift;

    print "argument: $argument\n";
}


package main;


require GENESIS3;


