#!/usr/bin/perl -w
#!/usr/bin/perl -d:ptkdb
#!


use strict;


BEGIN
{
    #! make check

    push @INC, '../perl';

    #! make distcheck

    push @INC, '../../perl';

    #! normal run

    push @INC, './perl';

    #! after install

    push @INC, '/usr/local/glue/swig/perl';
}


BEGIN
{
    $ENV{NEUROSPACES_NMC_MODELS} = '/usr/local/neurospaces/models/library';
}


$SIG{__DIE__}
    = sub {
	use Carp;

	confess @_;
    };


use GENESIS3;


package GENESIS3::Commands;


component_load("chemesis3");

ndf_load("chemesis/cal2.ndf");

chemesis3_set_timestep(0.002);

output_add("/cal2/soma/cal1/Ca", "concentration");
output_add("/cal2/soma/cal1/Cabuf", "concentration");
output_add("/cal2/soma/cal1/buf", "concentration");

output_add("/cal2/dend/cal1/Ca", "concentration");
output_add("/cal2/dend/cal1/Cabuf", "concentration");
output_add("/cal2/dend/cal1/buf", "concentration");

run("/cal2", 2);

