#!/usr/bin/perl -w
#!/usr/bin/perl -d:ptkdb
#!


use strict;


BEGIN
{
    #! make check

    push @INC, '../perl';

    #! make distcheck

    push @INC, '../../perl';

    #! normal run

    push @INC, './perl';

    #! after install

    push @INC, '/usr/local/glue/swig/perl';
}


BEGIN
{
    $ENV{NEUROSPACES_NMC_MODELS} = '/usr/local/neurospaces/models/library';
}


$SIG{__DIE__}
    = sub {
	use Carp;

	confess @_;
    };


use GENESIS3;


package GENESIS3::Commands;


ndf_load("tests/cells/singlep.ndf");

output_mode("steps");

output_format(" %.3f");

heccer_set_timestep(1e-5);

run("/singlep", 0.001);


GENESIS3::Interactive::loop();

