#!/usr/bin/perl -w
#!/usr/bin/perl -d:ptkdb
#!


use strict;


BEGIN
{
    #! make check

    push @INC, '../perl';

    #! make distcheck

    push @INC, '../../perl';

    #! normal run

    push @INC, './perl';

    #! after install

    push @INC, '/usr/local/glue/swig/perl';
}


BEGIN
{
    $ENV{NEUROSPACES_NMC_MODELS} = '/usr/local/neurospaces/models/library';
}


$SIG{__DIE__}
    = sub {
	use Carp;

	confess @_;
    };


use GENESIS3;


print "loading purkinje cell\n";
GENESIS3::Commands::ndf_load("cells/purkinje/edsjb1994.ndf");
print "loaded\n";

print "setting endogenous frequencies\n";
GENESIS3::Commands::set_runtime_parameter("thickd::gaba::/Purk_GABA", "FREQUENCY", 1);
GENESIS3::Commands::set_runtime_parameter("spine::/Purk_spine/head/par", "FREQUENCY", 25);

GENESIS3::Commands::add_output("/Purkinje/segments/soma", "Vm");
GENESIS3::Commands::add_output("/Purkinje/segments/soma/ca_pool", "Ca");
GENESIS3::Commands::add_output("/Purkinje/segments/b0s01[0]", "Vm");

print "running for 0.1sec\n";
GENESIS3::Commands::run("/Purkinje", 0.1);


